package com.example.sneakerpuzzshop.utils.ui

const val ROUTE_LOGIN = "login"
const val ROUTE_SIGNUP = "signup"
const val ROUTE_HOME = "home"
const val ROUTE_FORGET_PW = "forget_pw"
const val ROUTE_SPLASH = "splash"
const val ROUTE_CATEGORY_PRODUCTS = "category_products/"
const val ROUTE_PRODUCTS_DETAILS = "product_details/"
const val ROUTE_PRODUCT_REVIEW = "/review"
const val ROUTE_CHECKOUT = "checkout"
const val ROUTE_THANK_YOU = "thank_you"
const val ROUTE_EDIT_PROFILE = "editprofile"
const val ROUTE_EDIT_PROFILE_FIELD_NAME = "editprfield_name"
const val ROUTE_EDIT_PROFILE_FIELD_PHONE = "editprfield_phone"
const val ROUTE_EDIT_PROFILE_FIELD_ADDRESS = "editprfield_address"
const val ROUTE_EDIT_PROFILE_FIELD_PASSWORD = "editprfield_password"
const val ROUTE_ORDER = "order/"
const val ROUTE_ORDER_DETAILS = "order_details/"